### PR TITLE
Added dutch national flag algo, sjf scheduling and lru page replacement algorithms 

### LINKED ISSUE #661: [NEW ALGORITHM] Dutch National Flag Algorithm
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Dutch National Flag Algorithm

### About:  
The Dutch National Flag Algorithm, by Edsger Dijkstra, sorts an array of three distinct elements into three parts: values less than, equal to, and greater than a pivot. It uses three pointers—low for elements less than the pivot, mid for current element processing, and high for elements greater than the pivot—sorting the array in a single pass.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [X ] Contributor in GSSoC-ext
- [X ] Want to work on it

### PR DESCRIPTION
**Pull request by meghanakn473**
Dutch National Flag Algorithm: A sorting algorithm that partitions an array into three sections based on a pivot value, typically used to sort elements into groups like red, white, and blue.

SJF (Shortest Job First) Scheduling: A CPU scheduling algorithm that selects the process with the shortest execution time to run next, minimizing average waiting time but can cause starvation for longer jobs.

LRU (Least Recently Used) Page Replacement: A memory management technique that replaces the page that has not been used for the longest time, optimizing cache usage in systems.

closes #661 
#683 
#684

### CODE REVIEW

**Comment by meghanakn473** [comment]
@pankaj-bind please check properly and allow merge !!

**Comment by meghanakn473** [comment]
@pankaj-bind Please reopen the issue and  reviews it correctly !!!

**Comment by meghanakn473** [comment]
@pankaj-bind ??

**Comment by meghanakn473** [comment]
Hey @pankaj-bind can I know if ur going to consider this or not?

**Comment by meghanakn473** [comment]
> @pankaj-bind hey why duplicate?
> I have deleted the previous pr and made new one
> 

@pankaj-bind !!!?

**Comment by pankaj-bind** [comment]
@meghanakn473 merged

**Comment by meghanakn473** [comment]
@pankaj-bind  I hv added 3 algorithms in one pr only yet u gave level 1, I would appreciate if u properly check n assign level 3

**Pull request merged**
