### PR TITLE
 FCFS scheduling algorithm

### PR DESCRIPTION
**Pull request by JSLSasiRekha**
The First-Come, First-Serve (FCFS) scheduling algorithm is a straightforward method used in operating systems to schedule processes based on their arrival time. It ensures fairness by executing processes in the exact order they arrive, making it ideal for batch systems and simple applications. FCFS is easy to implement but may cause the convoy effect, where shorter processes wait behind longer ones, leading to high average waiting times. It is non-preemptive, meaning a process runs to completion once started. Though less efficient for interactive systems, FCFS works well in environments where task order matters more than response time

### CODE REVIEW

**Comment by pankaj-bind** [comment]
Issue number not found

**Comment by JSLSasiRekha** [comment]
https://github.com/AlgoGenesis/C/issues/702

Issue number is 702 , Here is the attached link of it.
Could you please crosscheck this.

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
{E4907910-668E-4C92-9FC2-286F0C6AA9ED}
improper structure, do it inside miscellaneous

**Comment by JSLSasiRekha** [comment]
Changed the structure

**Comment by pankaj-bind** [comment]
no suitable changes were made.

**Pull request closed without merging**
