### PR TITLE
Addition of Tree Algoritms

### PR DESCRIPTION
**Pull request by Salini-sat**
Different Tree Algorithms has been done such as 
- Binary Tree
- AVL Tree 
- Splay Tree
And their operations such as 
-Insertion
-Traversal
- Searching
- Deletion

### CODE REVIEW

**Comment by Salini-sat** [comment]
The file "commited" contains all the mentioned code . Please look for it

**Comment by pankaj-bind** [comment]
Do not make PR until I assign

**Comment by Salini-sat** [comment]
but you assigned it to me
Screenshot 2024-10-02 195309

**Comment by Salini-sat** [comment]
For more reference - 
Screenshot 2024-10-02 195455
If some confusion or mistake from my end please clarify

**Pull request closed without merging**
