### PR TITLE
Word Search in a 2D Grid

### LINKED ISSUE #1238: [NEW ALGORITHM] Word Search in a 2D Grid Using Backtracking in C
#  Word Search in a 2D Grid Using Backtracking in C

### About:  
This algorithm solves the Word Search problem in a 2D grid using a backtracking approach. The objective is to determine if a given word can be constructed from adjacent cells in the grid, moving vertically or horizontally.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

### PR DESCRIPTION
**Pull request by Bhoomysingh10**
Fixes #1238 

# Word Search in 2D Grid Using Backtracking

This program determines if a given word can be found in a 2D grid of letters by connecting adjacent cells horizontally or vertically. It utilizes recursive backtracking to explore possible paths while ensuring each cell is used only once. The output is a boolean value indicating whether the word exists in the grid.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
not assigned

**Comment by Bhoomysingh10** [comment]
Sir What is the issue?

**Comment by Bhoomysingh10** [comment]
You have only assigned this issue to me, how come it is not assigned as per you ?

**Comment by pankaj-bind** [comment]
{0A651643-3717-477F-A239-B456704B3DE7}
You should mention your issue number in your PR, I have already made clear instructions for PR requests. Now, remove unnecessary files and keep only Program.c and README.md file

**Comment by pankaj-bind** [comment]
You should always mention your issue number in your PR, I have already made clear instruction for that. Now you have to remove .exe file.

**Comment by Bhoomysingh10** [comment]
@pankaj-bind Sir completed !

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
