### PR TITLE
#11 Added DFS

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added DFS Please check it.
also I want to add Sorting Algos.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
Change folder name as Depth First Search

**Comment by Shariq2003** [comment]
ok @pankaj-bind

**Comment by pankaj-bind** [comment]
And do not make PR until I assign you, Read contribution guidelines.

**Comment by Shariq2003** [comment]
okay @pankaj-bind sir, sorry for this, as its my first time to open source

**Comment by pankaj-bind** [comment]
Mention the issue number, it will help me tracking which issue completed.

**Comment by pankaj-bind** [comment]
> okay @pankaj-bind sir, sorry for this, as its my first time to open source

Don't worry, it's fine. But you should maintain a decorum, it showcases a good developer.

**Pull request merged**
