### PR TITLE
Changed Best-First-Search 

### PR DESCRIPTION
**Pull request by Deeptig9138**
Changes and Fixes:
Memory Leak Fix: After a node is processed, it is immediately freed using free(currentNode). At the end of the search, any remaining nodes in the queue are freed as well.
Out-of-Bounds Check: Before enqueuing, a check (queue->size >= MAX_NODES) ensures that the queue does not exceed the maximum node limit.
Efficient Enqueue Operation: The priority queue is now implemented using a linked list, so inserting nodes based on heuristic value is done in constant time (O(1) to insert at the front or O(n) for arbitrary insertion).
Heuristic Initialization: Ensure that the heuristic values in the Graph structure are meaningful estimates of the cost to reach the goal. For demonstration purposes, I kept the heuristic values the same.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
create README.md file also, having details of the following algorithm

**Comment by pankaj-bind** [comment]
Readme file not written properly add more detail, you can refer this https://github.com/AlgoGenesis/C/blob/main/Dynamic%20Programming/Coin%20Change%20Problem/README.md

**Comment by Deeptig9138** [comment]
Done updating readme file

**Comment by pankaj-bind** [comment]
Good, since in future some other contributors would love to add more backtracking algorithm, that what why you can create a separate folder inside Backtracking Algorithms named "N-Queens Problem Solver" and transfer both Program and Readme file into it, you have shown good efforts that why I'm promoting it to "level3".
make this changes I'll merge it

**Comment by Deeptig9138** [comment]
done

**Comment by Deeptig9138** [comment]
Please add hacktoberfest label too @pankaj-bind

**Review by pankaj-bind — APPROVED** [review]

**Comment by aditya-bhaumik** [comment]
@pankaj-bind please reduce the level over here as well i have already mentioned why you need to make the change in the other pull request

**Pull request merged**
