### PR TITLE
proportional scheduling

### PR DESCRIPTION
**Pull request by khwaishchawla**

### CODE REVIEW

**Comment by khwaishchawla** [comment]
@pankaj-bind please review my PR

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
incorrect data i is not proportional scheduling

**Comment by khwaishchawla** [comment]
this is proportional scheduling also known as fair share scheduling

**Comment by pankaj-bind** [comment]
mention this detail in readme file

**Comment by khwaishchawla** [comment]
@pankaj-bind this algorithm has two names fair share and proportional scheduling

**Comment by khwaishchawla** [comment]
@pankaj-bind done with the changes requested

**Comment by khwaishchawla** [comment]
@pankaj-bind

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
