### PR TITLE
Added Rock-Paper-Scissors Game folder into the Miscellaneous Algorithms folder

### PR DESCRIPTION
**Pull request by iamasraful**
Issue no #347 . You didn't merge this before.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
#347 #539 resolved

**Comment by pankaj-bind** [comment]
move this folder inside Miscellaneous Algorithms folder

**Comment by iamasraful** [comment]
Okay

**Comment by iamasraful** [comment]
Added the Added Rock-Paper-Scissors Game folder into the Miscellaneous Algorithms folder.

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
