### PR TITLE
Added Pascal Triangle

### LINKED ISSUE #297: [NEW ALGORITHM] Pascals Triangle
## Description:
An algorithm that generates Pascal’s Triangle, where each element is the sum of the two elements directly above it

## Checklist:
- [X] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
Used math, dp

### PR DESCRIPTION
**Pull request by meghanakn473**
I have added the pascal triangle code in C language, commented the required things and attached along with Readme.md file.

closes #297 

@pankaj-bind please review and allow merge

### CODE REVIEW

**Comment by meghanakn473** [comment]
@pankaj-bind please update !

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
Add detailed explanation in Readme file

**Comment by meghanakn473** [comment]
@pankaj-bind check now

**Comment by meghanakn473** [comment]
@pankaj-bind ??

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
