### PR TITLE
Added new algorithm Binary Tree from inorder and preorder #1060

### PR DESCRIPTION
**Pull request by AnkitHazra**
Added new algorithm Binary Tree from inorder and preorder #1060. Please review and merge it

### CODE REVIEW

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
{0460BDAE-B53A-4630-9355-8E88E337F9C7}
remove .exe file, create two separate folders for inorder and preorder and write readme file properly.

**Comment by AnkitHazra** [comment]
Okay

**Comment by pankaj-bind** [comment]
reference: https://github.com/AlgoGenesis/C/tree/main/Recursion/Postorder
he have created postorder, now you have to create for preorder and postorder

**Comment by AnkitHazra** [comment]
> reference: https://github.com/AlgoGenesis/C/tree/main/Recursion/Postorder
> he have created postorder, now you have to create for preorder and inorder

Okay. I will make another pull request.

**Pull request closed without merging**
