### PR TITLE
Add Important concepts In Trie section

### PR DESCRIPTION
**Pull request by iking07**
Maximum XOR of Two Numbers and  K-th Lexicographical String added in the Trie section.

### CODE REVIEW

**Comment by iking07** [comment]
Please give a level2 and hacktober-fest label for this.

**Comment by pankaj-bind** [comment]
Mention issue number

**Comment by iking07** [comment]
Issue number is #415

**Comment by iking07** [comment]
@pankaj-bind 
Issue number https://github.com/AlgoGenesis/C/issues/415
Added issue number

**Comment by MastanSayyad** [comment]
@pankaj-bind Kindly look onto this PR, the issue was Assigned to him, reopen and merge the PR if applicable.

**Pull request closed without merging**
