### PR TITLE
RES.c

### PR DESCRIPTION
**Pull request by AshmitaBarthwal**
The Ripple Effect Scheduling (RES) algorithm prioritizes tasks based on their priority level, aiming to minimize disruptions to lower-priority tasks. It first sorts tasks by priority and calculates waiting and turnaround times. A "ripple effect" adjustment slightly reduces waiting time for lower-priority tasks when preceded by higher-priority tasks. This approach ensures high-priority tasks are handled efficiently while minimizing the impact on lower-priority ones.

### CODE REVIEW

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
add README.md file also with proper explanation and move it into Miscellaneous Algorithms folder

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
move this folder into Miscellaneous Algorithms folder

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind please check it once.

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Please Review it once.

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind please check it once.
Made the required changes.

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
