### PR TITLE
Added: Anagram Check Under Strings Algorithms

### LINKED ISSUE #1280: [NEW ALGORITHM] Anagram Check under String Algorithms
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Anagram Check```  

### About:  
It checks if two strings are anagrams, i.e. if they contain the same characters in the same frequency but in a different order.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Issue Resolved

- Closes #1280 

# Algorithm Added
**Anagram Check Algorithm**

# Description
The Anagram Check algorithm is used to determine if two strings are anagrams of each other. An anagram is a rearrangement(permutation) of the characters of one word or phrase to form another, using all the original characters exactly once. This algorithm can be useful in applications requiring string comparisons or pattern matching, such as spell-checking, cryptography, and text analysis.

```
Example:
str1 = This is true
str2 = Is this True

Output:
The strings are anagrams
```

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
@pankaj-bind Please review the PR and assign it to me with the necessary labels.

**Comment by rajdeepchakraborty-rc** [comment]
@pankaj-bind Also, can I open an issue now as I have completed working on this issue? I want to add a feature to your Repository, which cause me an issue when I was trying to contribute to your repository.

**Review by pankaj-bind — APPROVED** [review]

**Comment by rajdeepchakraborty-rc** [comment]
Thanks for reviewing the PR. Hope you have a great day ahead!

**Comment by rajdeepchakraborty-rc** [comment]
@pankaj-bind Also please assign me to this PR

**Pull request merged**
