### PR TITLE
Least Recently Used (LRU) Page Replacement Algorithm

### PR DESCRIPTION
**Pull request by meghanakn473**
closes: #684 
The Least Recently Used (LRU) Page Replacement Algorithm is a caching strategy used in operating systems to manage memory efficiently. It keeps track of page usage over time and evicts the least recently accessed page when a new page needs to be loaded into memory. By maintaining an accurate record of page access patterns, LRU minimizes page faults and optimizes the use of available frames, ensuring smoother and faster process execution.

### CODE REVIEW

**Comment by meghanakn473** [comment]
@pankaj-bind please review and allow merge and assign labels

**Comment by meghanakn473** [comment]
Heyy @pankaj-bind keeping leaderboard contest in mind....consider & review my 3 prs and allow merge and please assign level 3 gssoc-ext Hacktoberfest labels

**Comment by meghanakn473** [comment]
@pankaj-bind ??

**Comment by pankaj-bind** [comment]
resolve previous pr first

**Pull request closed without merging**
