### PR TITLE
Find the Duplicate Number

### PR DESCRIPTION
**Pull request by Dipanita45**
Given an array of n integers. The task is to find all elements that have more than one occurrences. The output should only one occurrence of a number irrespective of number of occurrences in the input array.

Issue No: #382 
Please review and label me

### CODE REVIEW

**Comment by pankaj-bind** [comment]
Program file missing

**Comment by Dipanita45** [comment]
Okay

**Comment by Dipanita45** [comment]
I will recheck and again make the pull request sir

**Comment by pankaj-bind** [comment]
code file missing

**Pull request closed without merging**
