### PR TITLE
Fixes #1259 Added Duck No. Algorithm 

### LINKED ISSUE #1259: [NEW ALGORITHM] Duck Number
## Issue will be closed if:

> 1) You mention more than one algorithm. Please create separate issues for each algorithm after the current one is completed.  
> 2) You propose an algorithm that already exists or is mentioned in a previous issue.  
> 3) You create a new issue without completing your previous one.

**Note:** These guidelines will be strictly followed. Non-compliance may result in the immediate closure of your issue.

---

### Name:  
```Duck Number```  

### About:  
Introduce an algorithm to identify **Duck Numbers**. A Duck Number is a positive number that contains at least one zero in any digit except the first. For example, 102 and 2405 are Duck Numbers, while 321 and 125 are not (since they either don’t have zeros or have one as the leading digit).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Interested contributors  

---

### PR DESCRIPTION
**Pull request by ShirshenduR**
### Pull Request for Duck Number Algorithm

**Issue Reference**: #1259

**Description**:  
This PR introduces an algorithm to identify **Duck Numbers**. A Duck Number is a positive integer that contains at least one `0` in any position except the first. This algorithm checks if a given integer meets these criteria.

**Changes Made**:
- Added a function `is_duck_number()` that:
  - Converts the integer to a string for easy digit-by-digit inspection.
  - Checks that the number does not start with `0`.
  - Confirms the presence of `0` in positions after the first digit.
- Updated documentation with examples and explanations in the `README.md` file for Duck Numbers.

**Example Cases**:
- Input: `405` → Output: Duck Number
- Input: `321` → Output: Not a Duck Number
- Input: `1205` → Output: Duck Number

**Additional Context**:  
This feature is commonly asked in coding interviews and serves as a fundamental problem in number property algorithms. It demonstrates basic control structures and string handling in C.

---

### Checklist
- [x] Code follows coding guidelines.
- [x] README updated with relevant information.
- [x] Tests included for example cases.

**Reviewers**: Please review and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by ShirshenduR** [comment]
@pankaj-bind Please review and merge and add the labels

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
Add more details in Readme.md

**Comment by ShirshenduR** [comment]
@pankaj-bind I updated the readme now please check

**Comment by ShirshenduR** [comment]
@pankaj-bind please merge it and add the labels

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
