### PR TITLE
transpose of a 2d matrx

### PR DESCRIPTION
**Pull request by PrasanBora**
This pull request introduces code to handle the transposition of a 2D matrix using three different approaches

**In-Place Transpose for Square Matrices:** This approach directly swaps elements across the diagonal without requiring additional space, optimizing for square matrices.

**Recursive Transpose:** Implements the transposition of the matrix recursively, providing a clear recursive solution for swapping elements across the diagonal

**Transpose into a New Matrix:** Transposes the matrix into a new result matrix, which works for both square and non-square matrices. This avoids modifying the original matrix

image

### CODE REVIEW

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
add readme file also and remove .exe file

**Comment by PrasanBora** [comment]
@pankaj-bind updated the code let me know any changes needed

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
{4F05D842-349D-4075-91C7-7656EAA3FDF1}
Readme file you have added is empty

**Comment by PrasanBora** [comment]
sorry for the confusion updated just now

**Comment by PrasanBora** [comment]
any particular suggestion for readme file

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
Explain properly in README file

**Comment by PrasanBora** [comment]
@pankaj-bind done

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
