### PR TITLE
Addition of Mathematical Algorithms

### PR DESCRIPTION
**Pull request by Deeptig9138**
I have added new Algorithms:
Shortest Path : Dijkstra, Floyd-Warshall etc
Minimum Spanning Tree: Prim's etc
Topological Order

### CODE REVIEW

**Comment by pankaj-bind** [comment]
#26

**Comment by aditya-bhaumik** [comment]
Hi @pankaj-bind,

I reviewed this pull request and noticed it's not a level 3 task.

Documentation updates should only be classified as level 1, and the other contributions are simple programs that can be easily found online or generated with AI tools like GPT, so they don't count as feature additions or bug fixes.

Your repo primarily contains README contributions and program submissions, so regardless of the number of lines, assign only level 1. Also, if contributors repeatedly make similar contributions, inform them that the limit for your type of repo is 150. Make sure to monitor this.

**Comment by aditya-bhaumik** [comment]
@pankaj-bind i am community manager of gssoc-extd please make sure to make this reduction in all the pull requests you have merged so far

**Comment by aditya-bhaumik** [comment]
@pankaj-bind please reply to me in discord

**Comment by aditya-bhaumik** [comment]
@pankaj-bind please reduce the level like i asked you to

**Pull request merged**
