### PR TITLE
Find the middle element of the linkedlist#466

### PR DESCRIPTION
**Pull request by Ananya-vastare**
A linked list is a data structure where each node contains data and a reference (or link) to the next node in the sequence. To solve this, one common approach is to use two pointers: a "slow" pointer that moves one step at a time and a "fast" pointer that moves two steps at a time. By the time the fast pointer reaches the end of the list, the slow pointer will be at the middle node. This method is efficient, with a time complexity of O(n) and no need for extra space.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
issue number not found

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
readme file missing

**Comment by Ananya-vastare** [comment]
@pankaj-bind will add the readme.md file

**Comment by Ananya-vastare** [comment]
@pankaj-bind I have added the file please look into it thank you

**Comment by pankaj-bind** [comment]
#466

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
