### PR TITLE
Feature/binary index tree

### PR DESCRIPTION
**Pull request by MahraibFatima**
Feature Details
 ---

# Binary Indexed Tree
### **Segment Tree**:
A segment tree is a binary tree used for answering range queries and updates efficiently in O(log n) time. It divides the array into segments and processes range operations like sum, min, or max over intervals. With modifications like lazy propagation, it can handle range updates without recalculating the entire tree.

### **Fenwick Tree**:
A Fenwick Tree is a compact data structure used for cumulative frequency tables and range queries. It efficiently supports prefix sum queries and point updates in O(log n) time, using an internal binary representation to propagate changes across nodes. It's simpler and often preferred for smaller use cases like frequency queries.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
issue number?

**Comment by MahraibFatima** [comment]
@pankaj-bind , here the issue [link](https://github.com/AlgoGenesis/C/issues/288#issue-2570951368)

**Comment by pankaj-bind** [comment]
image
You have to create separate folder for each and also readme files, do not include main.c, inside segment tree folder create 3 new folder to store those algorithms similarly do for fenwick

**Comment by MahraibFatima** [comment]
Sure!

**Comment by MahraibFatima** [comment]
@pankaj-bind kindly check now.

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
