### PR TITLE
Adding greedy Algorithm

### PR DESCRIPTION
**Pull request by lkksharma**
## Description:
Adding greedy algorithm code

## Issue Number:
Solving issue #58 

## Checklist:
 I am assigned for this.
 I have also created a README.md file for the following algorithm.

## Additional Information:
Explaining using the denomination problem.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
image
delete these files and add more detail in README.md

**Comment by pankaj-bind** [comment]
image
delete these files

**Comment by lkksharma** [comment]
The files have been deleted.

**Comment by lkksharma** [comment]
hi @pankaj-bind,
I request you to add the required labels i.e. ggsoc-ext and hacktoberfest-accepted.

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
