### PR TITLE
Added Hashmap data structure

### PR DESCRIPTION
**Pull request by Riya7045**
This fixes issue #1181

### CODE REVIEW

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
Add readme file also

**Comment by Riya7045** [comment]
Ok I will add

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
{C7F30823-0B4F-440A-893F-E4C54B8A104A}

It should be Program.c not implementation.cpp, correct this issue

**Comment by Riya7045** [comment]
ohkay

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
