### PR TITLE
Markov Chain Monte Carlo.

### PR DESCRIPTION
**Pull request by 13Sharad**
#1559

### CODE REVIEW

**Comment by 13Sharad** [comment]
@pankaj-bind please merged this pull request

**Comment by 13Sharad** [comment]
@pankaj-bind please merged this pull request

**Comment by 13Sharad** [comment]
@pankaj-bind please merged this pull request

**Comment by 13Sharad** [comment]
@pankaj-bind please merged this pull request

**Comment by 13Sharad** [comment]
@pankaj-bind please merged this pull request

**Comment by 13Sharad** [comment]
@pankaj-bind please merged this pull request

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
{B9D4B5CD-AF90-4309-BBE4-9FE020A513D8}
remove Program.exe file

**Comment by 13Sharad** [comment]
@pankaj-bind please merged this pull request

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
