### PR TITLE
I have added Graham Scan Algorithm

### PR DESCRIPTION
**Pull request by Sivasaiklu**

### CODE REVIEW

**Comment by Sivasaiklu** [comment]
@pankaj-bind, I have added graham scan algorith and created PR please check it and merge it sir

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
{88F81446-EBB9-40DF-AB69-FFA25935CA68}
remove unnecessary files.

**Comment by Sivasaiklu** [comment]
> {88F81446-EBB9-40DF-AB69-FFA25935CA68} remove unnecessary files.

@pankaj-bind now check

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
{E33F5C87-10A2-4907-8C9F-E7916E734343}
Remove bit manipulation folder and usage_output_complexity.txt

**Comment by Sivasaiklu** [comment]
> {E33F5C87-10A2-4907-8C9F-E7916E734343} Remove bit manipulation folder and usage_output_complexity.txt

ok sir

**Comment by Sivasaiklu** [comment]
Deleted sir, now check

**Comment by Sivasaiklu** [comment]
@pankaj-bind sir add the hacktoberfest label sir please

**Comment by pankaj-bind** [comment]
move this miscellaneous algorithm folder

**Comment by Sivasaiklu** [comment]
@pankaj-bind moved to miscellaneous algorithm folder sir, check once

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
