### PR TITLE
 addition of more DP related problems (Issue #45)

### PR DESCRIPTION
**Pull request by simmi-verma**
I have solved DP related problems

### CODE REVIEW

**Comment by pankaj-bind** [comment]
#45
{7615042C-CC13-41D4-8C51-68BCCC493F13}
remove .exe files and add Readmme.md files also add more detail in readme files

**Comment by simmi-verma** [comment]
Ok

**Comment by pankaj-bind** [comment]
wait you are not assigned to change this much.
you have to add only these
House Robber
Maximum sum of non-adjacent elements
as you are assigned in issue #45, delete everything and create a new PR.

**Comment by simmi-verma** [comment]
Ok sir

**Comment by simmi-verma** [comment]
Sir I have solved this issue

**Comment by simmi-verma** [comment]
Please merge my issue

**Pull request closed without merging**
