### PR TITLE
Added linkedlist concept

### PR DESCRIPTION
**Pull request by AnshDwivedi03**

### CODE REVIEW

**Comment by Shariq2003** [comment]
@pankaj-bind , i have raised this issue, and @AnshDwivedi03 has created a PR without even being assigned by you.
Please resolve close this PR as its duplicate, and assigned my issue to me #180

**Comment by AnshDwivedi03** [comment]
@Shariq2003  first of all raising issue is not the big deal, secondly you should work fast and raise ur pr .., you are too slow kindly work on ur ability

**Comment by Shariq2003** [comment]
> @Shariq2003 first of all raising issue is not the big deal, secondly you should work fast and raise ur pr .., you are too slow kindly work on ur ability

What 😂, bro, this is open source in which there are multiple projects, and currently I am working on multiple projects.
Raising a PR without even being assigned by anyone is not an ability. You just found an issue without doing any research on the GitHub repo and just raised a PR for it and called this the so-called Ability.
If this is an ability then sorry I am not able like you.

**Comment by Upendra48** [comment]
@Shariq2003 @AnshDwivedi03  Guys I have been working of Linked List, from the beginning and that Linked List folder was created by me, and I am still working on it.
What I have been doing is that, I am creating an issue, and waiting for the admin to assign it to me before creating a pull request, **following the contributing guidelines**. So I request you to find some other issue or raise your own rather than this one and about Linked List as I am working on it.

**Comment by AnshDwivedi03** [comment]
@Upendra48 With due respect.., I know many are working on it But the point is who is faster , Creating folder is not too big thing . You raise your pr if admin approve it's good. This is a race and the one who works fast always win

**Comment by Upendra48** [comment]
@AnshDwivedi03 
Kindly read contribution guidelines,
Thank you

**Comment by Shariq2003** [comment]
> @AnshDwivedi03 Kindly read contribution guidelines, Thank you

@Upendra48 don't waste your time in explaining @AnshDwivedi03 about how to contribute and read contributing.md.
This huy is insane.
Lightning fast.

**Comment by AnshDwivedi03** [comment]
@Shariq2003 Lol.., you are assigned and haven't raised pr till now.. Knowledge <<< 
I raised pr within an hr. Knowledge >>>.
Kids

**Comment by Shariq2003** [comment]
@AnshDwivedi03 
image

If No assignees means Shariq is assigned then I am blind and fortunately u got the super powers

**Comment by pankaj-bind** [comment]
Do not raise PR until I assign you.

**Pull request closed without merging**
