### PR TITLE
added Stalin Algorithm

### PR DESCRIPTION
**Pull request by chandru110**
Stalin Sort Algorithm in C
Overview
Stalin Sort is a humorous and non-standard sorting algorithm that sorts numbers by "purging" any elements that are out of order. This means it keeps only those elements that are in non-decreasing order relative to the previously kept element. The result is a sorted sequence of numbers, though some of the original elements may be "purged" or ignored.

How It Works
Start with the first number as the initial element in the sorted sequence.
For each subsequent number:
If the current number is greater than or equal to the last kept number, add it to the sorted sequence.
If the number is smaller, ignore it.
Continue this process until all elements have been evaluated, producing a sorted sequence that only includes numbers in non-decreasing order.
Features
Simple algorithm that illustrates selection criteria by "purging" out-of-order elements.
Creates a sorted sequence but may omit certain numbers.
Best suited for educational or humorous purposes, as it lacks practical efficiency for general sorting.

Limitations
Stalin Sort is a humorous algorithm that only retains elements that maintain a non-decreasing sequence; thus, it does not perform a full sort.
It is not suitable for general sorting tasks or large datasets, as it only provides a partial, order-preserving result.

### CODE REVIEW

**Comment by chandru110** [comment]
Added a new sorting algo called Stalin Sort

**Comment by pankaj-bind** [comment]
not assigned

**Comment by chandru110** [comment]
I have created an issue kindly assign me and open this PR

**Comment by chandru110** [comment]
I got assigned so please kindly review and merge it

**Comment by chandru110** [comment]
> not assigned
This has been assigned to me

**Comment by chandru110** [comment]
So please do check it and merge it because it has been assigned to me

**Pull request closed without merging**
