### PR TITLE
 FCFS.c

### PR DESCRIPTION
**Pull request by AshmitaBarthwal**
The following FCFS algorithm code does-

Defines Process Details: Sets up a structure to store key information for each process, like its ID, time needed to complete (burst time), and the time it arrives in the system.

Schedules Processes: Sorts the processes by arrival time and calculates when each one will start and finish based on this order, ensuring they’re executed in the right sequence.

Calculates Key Metrics: Computes three important metrics for each process: response time (how long until it starts), turnaround time (total time from arrival to completion), and waiting time (time spent waiting to be processed).

Memory Management: Allocates memory for storing metrics and ensures that this memory is freed up once the calculations are complete to keep the program efficient.

Displays Results in a Table: Outputs all the process details and metrics in a neat, easy-to-read table format, showing each process’s burst time, arrival time, start time, completion time, and the calculated metrics.

### CODE REVIEW

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Please Review my PR

**Comment by pankaj-bind** [comment]
you haven't added README.md file

**Comment by AshmitaBarthwal** [comment]
Added the readme.md file @pankaj-bind

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
add more details in readme file

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
