### PR TITLE
Cycle Detection in a Directed Graph (Using DFS)

### PR DESCRIPTION
**Pull request by Ananya-vastare**
Cycle detection in a directed graph using Depth-First Search (DFS) works by exploring each node and tracking visited nodes in two ways: a *visited* set for nodes that have been completely processed, and a *recursion stack* for nodes currently in the DFS path. Starting from any unvisited node, DFS recursively visits its neighbors. If it encounters a node that is in the recursion stack, a cycle is detected since this indicates a back edge, where a node links back to an ancestor in the DFS path. Once all neighbors are processed, the node is removed from the recursion stack and marked as fully visited.

Issue NO:#1752

### CODE REVIEW

**Comment by Ananya-vastare** [comment]
@pankaj-bind please let me know if there are any issues thank you

**Review by pankaj-bind — CHANGES_REQUESTED** [review]
{A98CC327-B5FE-4881-8BFE-4853055C8F43}
delete extra files

**Comment by Ananya-vastare** [comment]
@pankaj-bind I have made the changes you can merge it now

**Comment by Ananya-vastare** [comment]
@pankaj-bind please review this the deadline is at 7:00pm

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
