### PR TITLE
#49 Addition of Backtracking Algos

### PR DESCRIPTION
**Pull request by Shariq2003**
Issue #49 

I have added two algorithms of Backtracking Algo.
1. N-Queen Problem Algorithm.
2. Sudoku Solver Problem Algorithm.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
Explain in brief in README Files

**Comment by Shariq2003** [comment]
> Explain in brief in README Files

@pankaj-bind Sir, I have added an in-depth explanation of each algo in the readme.md files
Please check and continue.

**Review by pankaj-bind — APPROVED** [review]

**Comment by Shariq2003** [comment]
@pankaj-bind sir, could u pleade add a level 2 for this PR as i have added two algos of backtracking with in-depth description and solution.

**Comment by NEGRAH-S** [comment]
@MastanSayyad , Basic readymade code addition can be added under Level 1

**Review by MastanSayyad — COMMENTED** [review]
algo addtions can only have level 1 no matter how many you add in a single PR! Even I can give you 10+ algos using chatgpt, github repos or internet

**Pull request merged**
