### PR TITLE
#48 Addition of Rabin Karp Algo

### PR DESCRIPTION
**Pull request by Shariq2003**
Issue #48 

I have added Rabin Karp Algorithm

### CODE REVIEW

**Comment by pratheekv39** [comment]
@pankaj-bind This appears to be a duplicate issue. In Issue #32, you have already assigned me the following algorithms:

1)Rabin Karp Algorithm
2)Aho-Corasick Algorithm
3)Z Algorithm
4)Levenshtein Distance Algorithm
5)Suffix Array Algorithm

Could you please review this to avoid duplication of effort? Thank you for your attention to this matter.

**Comment by Shariq2003** [comment]
@pratheekv39 I am the first one assigned by @pankaj-bind for this issue, also I have raised this issue first,
Also I have raise the PR too.

**Comment by pratheekv39** [comment]
@Shariq2003 Literally your Issue number is #48 and speaking of PR's ....Kindly look into the timestamps of PR's . I have submitted my PR way before you have . I still don't know why you are arguing . 
@pankaj-bind Kindly resolve this  issue please....

**Comment by Shariq2003** [comment]
@pratheekv39 you are right, I have noticed now, that you have added Rabin Karp in your Issue that named as More Algo....
that's why I was unable to see at that point in time and raised the Issue, well you are right

**Comment by pankaj-bind** [comment]
@Shariq2003 you can try others it is already there

**Pull request closed without merging**
