### PR TITLE
Aggressive Cows Problem

### PR DESCRIPTION
**Pull request by Dipanita45**
The Aggressive Cows problem is a classic algorithmic challenge that involves finding the maximum minimum distance to place cows in given positions. The goal is to maximize the minimum distance between any two cows while ensuring that a specified number of cows can be accommodated in the given positions.

Issue no: #379

Thank you for the chance and please review and label it.

### CODE REVIEW

**Comment by Dipanita45** [comment]
Please review my pull request @pankaj-bind

**Comment by pankaj-bind** [comment]
{3A2D0EAC-B2A6-4907-8E10-F00A8A345007}
delete this exe file

**Comment by Dipanita45** [comment]
What I will do now

**Comment by Dipanita45** [comment]
I had made the  deletion sir @pankaj-bind

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
