### PR TITLE
Added the Kadane's Algorithm

### PR DESCRIPTION
**Pull request by Bhumika-00**
Screenshot from 2024-10-09 16-23-14
Kadane's Algorithm is an efficient technique used to find the maximum sum of a contiguous subarray within a one-dimensional array of integers. It is particularly useful in scenarios where the input array may contain both positive and negative numbers. By leveraging a dynamic programming approach, Kadane's Algorithm can identify the maximum sum in linear time, making it optimal for large datasets.

### CODE REVIEW

**Comment by pankaj-bind** [comment]
You have submitted blanked file.

**Comment by pankaj-bind** [comment]
{1566546A-515C-4CF2-981F-060AD0CFD048}

**Comment by Bhumika-00** [comment]
Okay let me do it again

**Comment by Bhumika-00** [comment]
I have write the data ok wait let me check the issue and contact you ASAP

**Comment by Bhumika-00** [comment]
I have checked it

**Comment by pankaj-bind** [comment]
do you want to update?

**Review by pankaj-bind — APPROVED** [review]

**Comment by Bhumika-00** [comment]
Please assign me the next issue hare and tortoise algorithm

**Pull request merged**
