### PR TITLE
Bit Manipulation #47

### PR DESCRIPTION
**Pull request by simmi-verma**
##Bi Manipulation:

1. Check if the i-th Bit is Set:
 Added a function to determine if a specific bit in a number is set (i.e., equal to 1). This is useful for quick checks in algorithms, such  as flagging conditions or feature toggles.

2. Check if a Number is a Power of 2:
Implemented a method to verify if a given number is a power of 2 using bit manipulation, significantly reducing the complexity compared to traditional methods.

3.Swap Two Numbers:
Created a function to swap two numbers without using a temporary variable, utilizing XOR bit manipulation. This technique is memory-efficient and can be particularly useful in performance-sensitive scenarios.

I can make any other changes to this if needed.

### CODE REVIEW

**Comment by simmi-verma** [comment]
Hello sir, if there is any issue in my code. Please tell me , I will solve it.

**Comment by pankaj-bind** [comment]
@simmi-verma If possible, include some comments with your code to aid in comprehension.

**Comment by simmi-verma** [comment]
Ok sir

**Comment by simmi-verma** [comment]
I have done .

**Comment by simmi-verma** [comment]
Sir please reply me.

**Comment by simmi-verma** [comment]
Sir I am waiting for your reply.

**Comment by simmi-verma** [comment]
Sir please merge my PR.

**Comment by pankaj-bind** [comment]
#47

**Review by pankaj-bind — APPROVED** [review]

**Pull request merged**
